check50:
    files: &check50_files
        - !exclude "*"
        - !include "*.java"
        - !include "*.class"
        - !require "HistoNode.java"
        - !require "HistoList.java"
        - !require "Grader.java"
        - !require "HistoNode.class"
        - !require "HistoList.class"
        - !require "Grader.class"

submit50:
    files: *check50_files
