check50:
    files: &check50_files
        - !exclude "*"
        - !include "*.java"
        - !include "*.class"
        - !require "Heap.java"
        - !require "HeapRunner.java"
        - !require "Grader.java"
        - !require "Heap.class"
        - !require "HeapRunner.class"


submit50:
    files: *check50_files
