check50:
    files: &check50_files
        - !exclude "*"
        - !include "*.java"
        - !include "*.class"
        - !require "IteratorReplacer.java"
        - !require "IteratorReplacer.class"
        - !require "IteratorReplacerRunner.java"
        - !require "IteratorReplacerRunner.class"
        - !require "Grader.java"
        - !require "Grader.class"

submit50:
    files: *check50_files
