check50:
    files:
        - !exclude "*"
        - !include "IteratorReplacer.java"
        - !include "IteratorReplacer.class"
        - !include "IteratorReplacerRunner.java"
        - !include "IteratorReplacerRunner.class"
        - !include "Grader.java"
        - !include "Grader.class"
