check50:
    files: &check50_files
        - !exclude "*"
        - !include "MyStack.java"
        - !include "MyStack.class"
        - !include "MyStackRunner.java"
        - !include "MyStackRunner.class"
        - !include "Grader.java"
        - !include "Grader.class"

submit50:
    files: *check50_files
