check50:
    checks:
        Test has three names:
            - run: python3 main.py
              stdout:
                - Number of names:
              stdin:
                - 3
              stdout:
                - Name:
              stdin:
                - John
              stdout:
                - Name:
              stdin:
                - David
              stdout:
                - Name:
              stdin:
                - Poston
              stdout:
                - First name: John
                - Middle names: ['David']
                - Last name: Poston
