check50:
    files:
        - !exclude "*"
        - !include "IteratorRemover.java"
        - !include "IteratorRemover.class"
        - !include "IteratorRemoverRunner.java"
        - !include "IteratorRemoverRunner.class"
        - !include "Grader.java"
        - !include "Grader.class"
